# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2ead1e4a97dbb40626cd2a70666dd26bd3e159fd45fb474054bbf8e877c3cda543e37e21524b3d3a436ef2498c5994197436bf2037503ffdef993f3144a6936

test:
  secret_key_base: 8fb32f04300a3eac1deba7b829cb6a990286d90f9911ce1d862f6b67a14125790cffa4c9737ff197a8ebe2420bf98e85ab62e49434ed548ef0b7d6227be38e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
